name: build

on:
  push:
    branches:
      - master
      - develop
      - build-matrix
  pull_request:
    branches:
      - master
      - develop
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and Test
    continue-on-error: false
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependency
        if: ${{ matrix.os == 'ubuntu-latest' }}
          run: |
            sudo apt-get install libatlas-base-dev libfftw3-dev libplplot-dev libcfitsio-dev
        if: ${{ matrix.os == 'mac-latest' }}
          run: |
            brew install atlas fftw plplot cfitsio
      - name: Build
        run: |
          ./autogen.sh
          ./configure
          make -j
          make check

